@baseUrl = https://8080-marcoweb-correcaotarefa-awujf9hf4c8.ws-us115.gitpod.io
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJBUEkgVGFyZWZhcyIsInN1YiI6ImFkbWluIiwiZXhwIjoxNzI1MzE0OTI0fQ.m5UFvnv-0ZPCuqQ8LlYF-L7Z0e6W-7trdhEIC18eA-E

###
GET {{baseUrl}}/tarefas
Authorization: Bearer {{token}}

###
POST {{baseUrl}}/tarefas
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "descricao": "Criar Formulário",
    "concluido": false
}

###
GET {{baseUrl}}/tarefas/4

###
PUT {{baseUrl}}/tarefas/1
Content-Type: application/json

{
    "descricao": "Testando Alteração",
    "concluido": false
}

###
DELETE {{baseUrl}}/tarefas/1
